HgWorkflow/Controllers/WorkOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HgWorkflow.DAL;
using HgWorkflow.Models;

namespace HgWorkflow.Controllers
{
    public class WorkOrdersController : Controller
    {
        private OurDbContext db = new OurDbContext();

        // GET: WorkOrders
        public ActionResult Index(string searchString)
        {
            if (Session["UserId"] != null)
            {
                var workordersearch = from wo in db.workOrders
                           select wo;
                if (!String.IsNullOrEmpty(searchString))
                {
                    workordersearch = workordersearch.Where(wo => wo.CustomerMobileNumber.Contains(searchString)
                                           || wo.WorkOrderId.Contains(searchString));

                                            return View(workordersearch.ToList());
                    //}
                    //else
                    //{
                    //    ModelState.AddModelError("", "No records found.");
                    //}

                }
            
                return View(db.workOrders.ToList());
            }
            else
            {
                return RedirectToAction("Login", "UserAccount");
            }
            
        }

        // GET: WorkOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = db.workOrders.Find(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }

        // GET: WorkOrders/Create
        public ActionResult Create()
        {
            if (Session["UserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login","UserAccount");
            }
            
        }

        // POST: WorkOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,WorkOrderId,GoldSmithName,CustomerName,CustomerMobileNumber,CustomerEmail,JewelleryDescription1,JewelleryDescription2,JewelleryDescription3,WorkToBeDone,WorkToBeDone2,WorkToBeDone3,AgentName,ProductGivenOn,DateProposed,DateAcceptedOrRejected,ProductToBeReturnedOn,AmountToBeCollected,AmountEstimate,Status,Comments")] WorkOrder workOrder)
        {

               if (ModelState.IsValid)
                {
                            
                    db.workOrders.Add(workOrder);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            
            return View(workOrder);

        }

        // GET: WorkOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = db.workOrders.Find(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }

        // POST: WorkOrders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,WorkOrderId,GoldSmithName,CustomerName,CustomerMobileNumber,CustomerEmail,JewelleryDescription1,JewelleryDescription2,JewelleryDescription3,WorkToBeDone,WorkToBeDone2,WorkToBeDone3,AgentName,ProductGivenOn,DateProposed,DateAcceptedOrRejected,ProductToBeReturnedOn,AmountToBeCollected,AmountEstimate,Status,Comments")] WorkOrder workOrder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workOrder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(workOrder);
        }

        // GET: WorkOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = db.workOrders.Find(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }

        // POST: WorkOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkOrder workOrder = db.workOrders.Find(id);
            db.workOrders.Remove(workOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HgWorkflow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title class="not-printable">@ViewBag.Title -Hallbergs-Workorder</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/NewStyle.css" rel="stylesheet" />
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top not-printable">
        @*<div class="container">
            @*<div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
        @*@Html.ActionLink("Work Order", "", "", new { area = "" }, new { @class = "navbar-brand" })
            </div>*@
        @if (Session["UserId"] != null)
        {
            <div class="navbar-collapse collapse not-printable">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Reparationer", "Index", "WorkOrders")</li>
                    <li>@Html.ActionLink("Ny Reparation", "Create", "WorkOrders")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Logga ut", "Logout", "UserAccount")</li>
                </ul>
            </div>

        }
    </div>
    @if (Session["UserId"] != null)
    {
        <div class=" not-printable">
        <div class="alert-success">Välkommen <b>@Session["Fullname"]</b></div>
        </div>
    }
    @RenderBody()
    <hr />

    <footer class="text-center not-printable">
        <p>ikraftorG AB. for HallBergs Guld &copy; @DateTime.Now.Year</p>
    </footer>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>